---
title: "EMPA Vegetation Analysis"
author: "Brooke Fulkerson"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{EMPA Vegetation Analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(EMPAFunctionAnalysis)
```

# Load Data

```{r load-data}
Veg <- load_veg_data()
Veg_metadata <- load_veg_metadata()
CRAM <- load_cram_data()
Rugged <- load_ruggedness_data()
```

# Clean Data

```{r clean-data}
Veg <- Veg |> clean_veg() |> order_veg()
veg_metadata_clean <- Veg_metadata |> clean_veg_metadata() |> order_veg_metadata()
```

# Figures

## CRAM CDFs

```{r cram-index}
plot_cram_cdf(CRAM,
              state_col = "indexscore",
              empa_col  = "EMPA_index",
              title     = "Statewide CRAM Scores 2014 - 2024",
              x_label   = "CRAM Index Score")
```

```{r cram-biotic}
plot_cram_cdf(CRAM,
              state_col = "biotic_structure",
              empa_col  = "EMPA_bio",
              title     = "Statewide Biotic Attribute Scores 2014 - 2024",
              x_label   = "Biotic Attribute Score")
```

```{r cram-physical}
plot_cram_cdf(CRAM,
              state_col = "physical_structure",
              empa_col  = "EMPA_phys",
              title     = "Statewide Physical Attribute Scores 2014 - 2024",
              x_label   = "Physical Attribute Score")
```

## Native Vegetation

```{r veg-abundance}
plot_veg_abundance(Veg, year = "2023", season = "Fall")
```

## Vegetated Cover

```{r veg-cover}
plot_veg_cover(veg_metadata_clean, year = "2023")
```

# Scoring

```{r scoring}
cram_summary     <- score_cram(CRAM, function_name = "Plant")
veg_rel_summary  <- score_veg_relative(Veg)
invasive_summary <- score_invasive_severity(Veg)
veg_cov_summary  <- score_veg_cover(veg_metadata_clean)
rugged_summary   <- score_ruggedness(Rugged)
```

# Final Dashboard Table

```{r dashboard}
dashboard_table_veg <- build_veg_dashboard(
  cram_summary, veg_rel_summary, veg_cov_summary,
  rugged_summary, invasive_summary
)

head(dashboard_table_veg)
```
