---
title: "EMPA_SLR_Code"
author: "Brooke Fulkerson"
date: "2025-06-13"
output: html_document
editor_options: 
  chunk_output_type: console
---

#Load Packages

```{r load packages}

library(ggplot2)
library(tidyverse)
library(tidyr)
library(ggrepel)

```

#Load Data

```{r load data}

wetland_extents <- read.csv("Data/HabitatZones_260224.csv")

CRAM <- read.csv("Data/EMPA_CRAM_2014-2024.csv")

Veg_metadata <- read.csv("https://nexus.sccwrp.org/empachecker/export?tablename=tbl_vegetation_sample_metadata")

GIS_data <- read.csv("Data/BufferLandCover_251203.csv") 

```

#Clean Data

##Wetland Extents

```{r order wetland data}

wetland_extents$Cover_class <- factor(wetland_extents$Cover_class, levels = c('Other', 'Upland', 'High', 'Mid', 
                                                                              'Low', 'Water', ordered = TRUE))

wetland_extents$Site_ID <- factor(wetland_extents$Site_ID, levels = c('NC-TEN', 'NC-BIGR', 'NC-NAV', 'NC-DRA', 'NC-BOL',
                                                        'CC-PAJ', 'CC-MCS', 'CC-CAR', 'CC-ADLC', 'CC-MOR',
                                                        'SC-GOL', 'SC-VEN', 'SC-MAL', 'SC-BOL', 'SC-NEW', 'SC-BAT'),
                           ordered = TRUE)

wetland_extents$Region <- factor(wetland_extents$Region, levels = c('North', 'Central', 'South',
                                                                    ordered = TRUE))

wetland_extents$Extent <- factor(wetland_extents$Extent, levels = c('Current Wetland Footprint', 'Wetland Migration/Avoid Developed (1.2 ft)', 'Wetland Migration/All Areas (1.2 ft)',
                                                                    ordered = TRUE))

```

##Veg Metadata

```{r clean veg metadata}

#convert to long format
veg_metadata_long <- Veg_metadata %>%
  select(siteid, habitat, samplecollectiondate, vegetated_cover, non_vegetated_cover) %>%
  pivot_longer(
    cols = c(vegetated_cover, non_vegetated_cover),
    names_to = "cover_type",
    values_to = "cover_value")

#clean data
veg_metadata_clean <- veg_metadata_long %>%
  mutate(Season = case_when(
    str_detect(samplecollectiondate, "2021-09") ~ "Fall",
    str_detect(samplecollectiondate, "2021-10") ~ "Fall",
    str_detect(samplecollectiondate, "2021-11") ~ "Fall",
    str_detect(samplecollectiondate, "2021-03") ~ "Spring",
    str_detect(samplecollectiondate, "2021-04") ~ "Spring",
    str_detect(samplecollectiondate, "2021-05") ~ "Spring",
    str_detect(samplecollectiondate, "2022-03") ~ "Spring",
    str_detect(samplecollectiondate, "2022-04") ~ "Spring",
    str_detect(samplecollectiondate, "2022-10") ~ "Fall",
    str_detect(samplecollectiondate, "2022-12") ~ "Fall",
    str_detect(samplecollectiondate, "2023-03") ~ "Spring",
    str_detect(samplecollectiondate, "2023-04") ~ "Spring",
    str_detect(samplecollectiondate, "2023-05") ~ "Spring",
    str_detect(samplecollectiondate, "2023-06") ~ "Spring",
    str_detect(samplecollectiondate, "2023-07") ~ "Spring",
    str_detect(samplecollectiondate, "2023-09") ~ "Fall",
    str_detect(samplecollectiondate, "2023-10") ~ "Fall",
    str_detect(samplecollectiondate, "2023-11") ~ "Fall",
    str_detect(samplecollectiondate, "2023-12") ~ "Fall")) %>%
  mutate(Year=case_when(
    str_detect(samplecollectiondate, "2021") ~ "Year 1",
    str_detect(samplecollectiondate, "2023") ~ "Year 2",
    str_detect(samplecollectiondate, "2024") ~ "Year 3")) %>%
  mutate(Habitat_final=case_when(
    habitat == "Mid marsh" ~ "Mid Marsh",
    habitat == "High marsh" ~ "High Marsh",
    habitat == "Channel" ~ "Low Marsh",
    habitat == "Upland" ~ "Upland",
    habitat == "Low marsh" ~ "Low Marsh",
    habitat == "Unvegetated salt panne" ~ "High Marsh",
    habitat == "Brackish marsh" ~ "High Marsh",
    habitat == "Not recorded" ~ "Not recorded",
    habitat == "site-wide" ~ "site-wide")) %>%
  mutate(estuaryname=case_when(
    siteid == "NC-TEN" ~ "Ten Mile River",
    siteid == "NC-BIGR" ~ "Big River",
    siteid == "NC-NAV" ~ "Navarro River",
    siteid == "NC-DRA" ~ "Drakes Estero",
    siteid == "NC-BOL" ~ "Bolinas Lagoon",
    siteid == "CC-PAJ" ~ "Pajaro River",
    siteid == "CC-MCS" ~ "Moro Cojo Slough",
    siteid == "CC-CAR" ~ "Carmel River",
    siteid == "CC-ADLC" ~ "Arroyo de la Cruz",
    siteid == "CC-MOR" ~ "Morro Bay",
    siteid == "SC-GOL" ~ "Goleta Slough",
    siteid == "SC-VEN" ~ "Ventura River",
    siteid == "SC-MAL" ~ "Malibu Lagoon",
    siteid == "SC-BOL" ~ "Bolsa Chica",
    siteid == "SC-NEW" ~ "Newport Bay",
    siteid == "SC-BAT" ~ "Batiquitos Lagoon"
  ))

```

```{r order veg metadata}

veg_metadata_clean$siteid <- factor(veg_metadata_clean$siteid, levels = c('NC-TEN', 'NC-BIGR', 'NC-NAV', 'NC-DRA', 'NC-BOL',
                                                        'CC-PAJ', 'CC-MCS', 'CC-CAR', 'CC-ADLC', 'CC-MOR',
                                                        'SC-GOL', 'SC-VEN', 'SC-MAL', 'SC-BOL', 'SC-NEW', 'SC-BAT'),
                           ordered = TRUE)

```

##GIS Data

```{r order GIS data}

GIS_data$siteid <- factor(GIS_data$siteid, levels = c('NC-TEN', 'NC-BIGR', 'NC-NAV', 'NC-DRA', 'NC-BOL',
                                                        'CC-PAJ', 'CC-MCS', 'CC-CAR', 'CC-ADLC', 'CC-MOR',
                                                        'SC-GOL', 'SC-VEN', 'SC-MAL', 'SC-BOL', 'SC-NEW', 'SC-BAT'),
                           ordered = TRUE)

GIS_data$landcover <- factor(GIS_data$landcover, levels = c('Developed', 'Ag', 'Natural', 'Total Buffer', 'Total Open', 'Largest Contiguous'),
                             ordered = TRUE)

```

#Plot Colors

```{r plot colors}

region_colors <- c("#56B4E9", "#009E73", "#F0E442")

MPA_colors <- c("#0072B2", "#D55E00")

mouth_colors <- c("#000000", "#CC79A7")

veg_colors <- c("#009900", "#3399FF", "#CC0033", "black")

habitat_colors <- c("#999999", "#0072B2", "#CC79A7")

elevation_colors <- c("#E69F00", "#F0E442", "#009E73", "#56B4E9")

veg_open_colors <- c("#999999", "#009E73")

land_cover_colors <- c("#CC0033", "#F0E442", "#009E73")

```

#Function Analysis

##Figures

###CRAM

```{r CRAM CDF - Index}

#create empirical CDF function with state data
cdf_fn_i <- ecdf(CRAM$indexscore)

#calculate CDF y-values for EMPA sites
CRAM$index_y <- cdf_fn_i(CRAM$EMPA_index)

#plot CDF for Index scores
CRAM_index_CDF <- CRAM %>%
  ggplot(aes(indexscore)) +
  stat_ecdf(geom = "step",
            color = "black",
            linewidth = 1) +
  theme_bw() +
  xlab("CRAM Index Score") +
  ylab("% of Population") +
  ggtitle("Statewide CRAM Scores 2014 - 2024") +
  scale_y_continuous(breaks = seq(0,1,0.1), 
                     labels = seq(0,100,10)) +
  theme(plot.title = element_text(face="bold",
                                  size=18,
                                  hjust=0.5)) +
  theme(axis.title.x = element_text(face="bold",
                                    size=16),
        axis.text.x= element_text(size=16)) +
  theme(axis.title.y = element_text(angle=90, 
                                    face="bold", 
                                    size=16, 
                                    vjust=1.5),
        axis.text.y  = element_text(size=16)) +
  theme(legend.title = element_blank(),
        legend.text = element_text(size = 14)) +
  geom_point(aes(x = EMPA_index, 
                 y = index_y,
                 fill = EMPA_MPA),
             size = 3,
             shape = 21) +
  scale_fill_manual(values = MPA_colors, na.translate = F) +
  geom_text_repel(aes(x = EMPA_index,
                      y = index_y,
                      label = siteid),
                  size = 5,
                  nudge_y = 0.2,
                  hjust = 1,
                  direction = "y",
                  force = 2)

CRAM_index_CDF

```

```{r CRAM CDF - biotic}

#create empirical CDF function with state data
cdf_fn_b <- ecdf(CRAM$biotic_structure)

#calculate CDF y-values for EMPA sites
CRAM$biotic_y <- cdf_fn_b(CRAM$EMPA_bio)

#plot CDF for Index scores
CRAM_Bio_CFD <- CRAM %>%
  ggplot(aes(biotic_structure)) +
  stat_ecdf(geom = "step",
            color = "black",
            linewidth = 1) +
  theme_bw() +
  xlab("Biotic Attribute Score") +
  ylab("% of Population") +
  ggtitle("Statewide Biotic Attribute Scores 2014 - 2024") +
  scale_y_continuous(breaks = seq(0,1,0.1), 
                     labels = seq(0,100,10)) +
  theme(plot.title = element_text(face="bold",
                                  size=18,
                                  hjust=0.5)) +
  theme(axis.title.x = element_text(face="bold",
                                    size=16),
        axis.text.x= element_text(size=16)) +
  theme(axis.title.y = element_text(angle=90, 
                                    face="bold", 
                                    size=16, 
                                    vjust=1.5),
        axis.text.y  = element_text(size=16)) +
  theme(legend.title = element_blank(),
        legend.text = element_text(size = 14)) +
  geom_point(aes(x = EMPA_bio, 
                 y = biotic_y,
                 fill = EMPA_MPA),
             size = 3,
             shape = 21) +
  scale_fill_manual(values = MPA_colors, na.translate = F) +
  geom_text_repel(aes(x = EMPA_bio,
                      y = biotic_y,
                      label = siteid),
                  size = 5,
                  nudge_y = 0.2,
                  hjust = 1,
                  direction = "y",
                  force = 2)

CRAM_Bio_CFD

```

```{r CRAM CDF - Physical}

#create empirical CDF function with state data
cdf_fn_p <- ecdf(CRAM$physical_structure)

#calculate CDF y-values for EMPA sites
CRAM$phys_y <- cdf_fn_p(CRAM$EMPA_phys)

#plot CDF for Index scores
CRAM_Phys_CFD <- CRAM %>%
  ggplot(aes(physical_structure)) +
  stat_ecdf(geom = "step",
            color = "black",
            linewidth = 1) +
  theme_bw() +
  xlab("Physical Attribute Score") +
  ylab("% of Population") +
  ggtitle("Statewide Physical Attribute Scores 2014 - 2024") +
  scale_y_continuous(breaks = seq(0,1,0.1), 
                     labels = seq(0,100,10)) +
  theme(plot.title = element_text(face="bold",
                                  size=18,
                                  hjust=0.5)) +
  theme(axis.title.x = element_text(face="bold",
                                    size=16),
        axis.text.x= element_text(size=16)) +
  theme(axis.title.y = element_text(angle=90, 
                                    face="bold", 
                                    size=16, 
                                    vjust=1.5),
        axis.text.y  = element_text(size=16)) +
  theme(legend.title = element_blank(),
        legend.text = element_text(size = 14)) +
  geom_point(aes(x = EMPA_phys, 
                 y = phys_y,
                 fill = EMPA_MPA),
             size = 3,
             shape = 21) +
  scale_fill_manual(values = MPA_colors, na.translate = F) +
  geom_text_repel(aes(x = EMPA_phys,
                      y = phys_y,
                      label = siteid),
                  size = 5,
                  nudge_y = 0.2,
                  hjust = 1,
                  direction = "y",
                  force = 2)

CRAM_Phys_CFD

```

###Veg Cover

```{r percent veg cover in upper marsh}

veg_open_cover <- veg_metadata_clean %>%
  filter(habitat != "Low marsh") %>%
  filter(habitat != "Upland") %>%
  filter(habitat != "Not recorded") %>%
  filter(habitat != "Unvegetated salt panne") %>%
  filter(siteid != "NA") %>%
  filter(Year == "Year 2") %>%
  ggplot(aes(y = cover_value,
             x = siteid,
             fill = cover_type)) +
  theme_bw() +
  scale_fill_manual(values = veg_open_colors,
                    labels = str_wrap(c("Non-Vegetated Cover", "Vegetated Cover"),
                                     width = 14)) +
  scale_x_discrete(limits = rev) +
  coord_flip() +
  geom_bar(position = "fill", stat = "identity") +
  ylab("Percent Cover") +
  xlab("Site ID") +
  ggtitle("Percent Vegetated Cover in Upper Marsh Habitats") +
  scale_y_continuous(labels = scales::percent_format(scale = 100)) +
  theme(strip.text.x = element_text(face = "bold", 
                                    size = 16)) +
  theme(plot.title = element_text(face="bold",
					                        size=18,
                                  hjust=0.5)) +
  theme(axis.title.y = element_text(angle=90, 
                                    face="bold", 
                                    size=16, 
                                    vjust=1.5),
        axis.text.y  = element_text(size=16)) +
  theme(axis.title.x = element_text(face="bold",
                                    size=16),
        axis.text.x= element_text(size=16)) +
  theme(legend.title = element_blank(),
        legend.text = element_text(size = 14))

veg_open_cover

```

###Upland Migration

####Buffer Landcover

#####500m

```{r landcover barcharts 500m buffer}

buffer_LC_500 <- GIS_data %>%
  filter(buffer == "500 m") %>%
  ggplot(aes(x = siteid,
             y = percent,
             fill = landcover)) +
  theme_bw() +
  scale_fill_manual(values = land_cover_colors) +
  geom_bar(position = "fill", stat = "identity") +
  scale_y_continuous(labels = scales::percent_format(scale = 100)) +
  xlab("Site ID") +
  ylab("Percent Cover") +
  ggtitle("Buffer Land Cover Class Distribution (500 m)") +
  theme(axis.title.x = element_text(face = "bold", 
                                    size = 16),
        axis.text.x = element_text(size = 8,
                                   angle = 45,
                                   hjust = 1),
        plot.title = element_text(face = "bold", 
                                  size = 18, 
                                  hjust = 0.5),
        axis.title.y = element_text(angle = 90, 
                                    face = "bold", 
                                    size = 16, 
                                    vjust = 1.5),
        axis.text.y = element_text(size = 12),
        legend.title = element_blank(),
        legend.text = element_text(size = 14),
        strip.text = element_text(face = "bold", 
                                  size = 10))

buffer_LC_500

```

#####30m

```{r landcover barcharts 30m buffer}

buffer_LC_30 <- GIS_data %>%
  filter(buffer == "30 m") %>%
  ggplot(aes(x = siteid,
             y = percent,
             fill = landcover)) +
  theme_bw() +
  scale_fill_manual(values = land_cover_colors) +
  geom_bar(position = "fill", stat = "identity") +
  scale_y_continuous(labels = scales::percent_format(scale = 100)) +
  xlab("Site ID") +
  ylab("Percent Cover") +
  ggtitle("Buffer Land Cover Class Distribution (30 m)") +
  theme(axis.title.x = element_text(face = "bold", 
                                    size = 16),
        axis.text.x = element_text(size = 8,
                                   angle = 45,
                                   hjust = 1),
        plot.title = element_text(face = "bold", 
                                  size = 18, 
                                  hjust = 0.5),
        axis.title.y = element_text(angle = 90, 
                                    face = "bold", 
                                    size = 16, 
                                    vjust = 1.5),
        axis.text.y = element_text(size = 12),
        legend.title = element_blank(),
        legend.text = element_text(size = 14),
        strip.text = element_text(face = "bold", 
                                  size = 10))

buffer_LC_30

```

#####Contiguous Open

```{r contiguous buffer barplots}

#Do we need a figure for this?

```

####Elevation

#####North

```{r north sites}

wet_hab_north <- wetland_extents %>%
  filter(Region == "North") %>%
  filter(Cover_class != "Other") %>%
  filter(Cover_class != "Upland") %>%
  ggplot(aes(x = Extent,
             y = Percent_cover,
             fill = Cover_class)) +
  theme_bw() +
  geom_bar(position = "fill", stat = "identity", width = 0.5) +
  facet_wrap(.~ Site_ID, ncol = 2) +
  xlab("Sea Level Rise") +
  ylab("Relative Cover") +
  ggtitle("Habitat Distribution Comparison") +
  scale_fill_manual(values=elevation_colors) +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 16)) +
  theme(axis.title.x = element_text(face = "bold", 
                                    size = 16),
        axis.text.x = element_text(size = 8),
        plot.title = element_text(face = "bold", 
                                  size = 18, 
                                  hjust = 0.5),
        axis.title.y = element_text(angle = 90, 
                                    face = "bold", 
                                    size = 16, 
                                    vjust = 1.5),
        axis.text.y = element_text(size = 12),
        legend.title = element_blank(),
        legend.text = element_text(size = 14),
        strip.text = element_text(face = "bold", 
                                  size = 10))

wet_hab_north

```

#####Central

```{r central sites}

wet_hab_central <- wetland_extents %>%
  filter(Region == "Central") %>%
  filter(Cover_class != "Other") %>%
  filter(Cover_class != "Upland") %>%
  ggplot(aes(x = Extent,
             y = Percent_cover,
             fill = Cover_class)) +
  theme_bw() +
  geom_bar(position = "fill", stat = "identity", width = 0.5) +
  facet_wrap(.~ Site_ID, ncol = 2) +
  xlab("Sea Level Rise") +
  ylab("Relative Cover") +
  ggtitle("Habitat Distribution Comparison") +
  scale_fill_manual(values=elevation_colors) +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 16)) +
  theme(axis.title.x = element_text(face = "bold", 
                                    size = 16),
        axis.text.x = element_text(size = 8),
        plot.title = element_text(face = "bold", 
                                  size = 18, 
                                  hjust = 0.5),
        axis.title.y = element_text(angle = 90, 
                                    face = "bold", 
                                    size = 16, 
                                    vjust = 1.5),
        axis.text.y = element_text(size = 12),
        legend.title = element_blank(),
        legend.text = element_text(size = 14),
        strip.text = element_text(face = "bold", 
                                  size = 10))

wet_hab_central

```

#####South

```{r south sites}

wet_hab_south <- wetland_extents %>%
  filter(Region == "South") %>%
  filter(Cover_class != "Other") %>%
  filter(Cover_class != "Upland") %>%
  ggplot(aes(x = Extent,
             y = Percent_cover,
             fill = Cover_class)) +
  theme_bw() +
  geom_bar(position = "fill", stat = "identity", width = 0.5) +
  facet_wrap(.~ Site_ID, ncol = 2) +
  xlab("Sea Level Rise") +
  ylab("Relative Cover") +
  ggtitle("Habitat Distribution Comparison") +
  scale_fill_manual(values=elevation_colors) +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 16)) +
  theme(axis.title.x = element_text(face = "bold", 
                                    size = 16),
        axis.text.x = element_text(size = 8),
        plot.title = element_text(face = "bold", 
                                  size = 18, 
                                  hjust = 0.5),
        axis.title.y = element_text(angle = 90, 
                                    face = "bold", 
                                    size = 16, 
                                    vjust = 1.5),
        axis.text.y = element_text(size = 12),
        legend.title = element_blank(),
        legend.text = element_text(size = 14),
        strip.text = element_text(face = "bold", 
                                  size = 10))

wet_hab_south

```

###Sediment Accretion (TBD)

#Scoring

##CRAM

```{r caluclating score for CRAM data}

CRAM_slr_summary <- CRAM %>%
  mutate(function_name = "SLR") %>%
  mutate(indicator_name = "habitat") %>%
  mutate(
    index_grade = round(((EMPA_index - 25) / 75) * 100, digits = 1)) %>%
  select(estuaryname, siteid, function_name, indicator_name, index_grade) %>%
  filter(!is.na(siteid)) %>%
  rename(index = index_grade)

```

##Veg Cover

```{r veg cover summary table}

#create a table with relative abundance for both cover classes
veg_cover <- veg_metadata_clean %>%
  filter(siteid != "NA") %>%
  filter(cover_value != "-88") %>%
  filter(estuaryname != "NA") %>%
  group_by(estuaryname, siteid, cover_type) %>%
  summarise(total_cover = sum(cover_value, na.rm = TRUE), .groups = "drop") %>%
  group_by(siteid) %>%
  mutate(
    relative_abundance = total_cover / sum(total_cover) * 100) %>%
  mutate(
    relative_abundance = round(relative_abundance, 1)) %>%
  select(estuaryname, siteid, cover_type, relative_abundance) %>%
  pivot_wider(
    names_from = cover_type,
    values_from = relative_abundance,
    values_fill = 0
  )

#create table with only vegetated cover

veg_cov_slr_summary <- veg_cover %>%
  mutate(function_name = "SLR") %>%
  mutate(indicator_name = "vegetation") %>%
  select(estuaryname, siteid, function_name, indicator_name, vegetated_cover) %>%
  rename(veg_cover = vegetated_cover)

```

##Upland Migration

###Buffers

####500 m

```{r 500m buffer summary table}

buffer_500_summary <- GIS_data %>%
  filter(buffer == "500 m") %>%
  mutate(landcover_group = case_when(
    landcover %in% c("Ag", "Natural") ~ "Ag_Natural_500",
    landcover == "Developed" ~ "Developed",
    TRUE ~ NA_character_
  )) %>%
  group_by(estuaryname, siteid, landcover_group) %>%
  summarise(total_percent = sum(percent, na.rm = TRUE),
            .groups = "drop") %>%
  pivot_wider(
    names_from = landcover_group,
    values_from = total_percent,
    values_fill = 0
  ) %>%
  mutate(function_name = "SLR") %>%
  mutate(indicator_name = "resiliency")

```

####30 m

```{r 30m buffer summary table}

buffer_30_summary <- GIS_data %>%
  filter(buffer == "30 m") %>%
  mutate(landcover_group = case_when(
    landcover %in% c("Ag", "Natural") ~ "Ag_Natural_30",
    landcover == "Developed" ~ "Developed",
    TRUE ~ NA_character_
  )) %>%
  group_by(estuaryname, siteid, landcover_group) %>%
  summarise(total_percent = sum(percent, na.rm = TRUE),
            .groups = "drop") %>%
  pivot_wider(
    names_from = landcover_group,
    values_from = total_percent,
    values_fill = 0
  ) %>%
  mutate(function_name = "SLR") %>%
  mutate(indicator_name = "resiliency")

```

####Contiguous

```{r contiguous buffer summary table}

buffer_contiguous_summary <- GIS_data %>%
  filter(landcover %in% c("Largest Contiguous", "Total Open")) %>%
  select(estuaryname, siteid, landcover, rastercount) %>%
  pivot_wider(
    names_from = landcover,
    values_from = rastercount
  ) %>%
  mutate(
    contiguous = if_else(
      `Total Open` > 0,
      round((`Largest Contiguous` / `Total Open`) * 100, 1),
      NA_real_
    )) %>%
  mutate(function_name = "SLR") %>%
  mutate(indicator_name = "resiliency")

```

####Elevation

#Final Table

```{r creating final SLR scoring table}

#Combine all small tables together

combined_table_slr <- bind_rows(CRAM_slr_summary, veg_cov_slr_summary, 
                            buffer_500_summary, buffer_30_summary, 
                            buffer_contiguous_summary) 

dashboard_table_slr <- combined_table_slr %>%
  select(-c(Developed, 'Total Open', 'Largest Contiguous')) %>%
  pivot_longer(
    cols = c(index, veg_cover, Ag_Natural_500, Ag_Natural_30, contiguous),
    names_to = "metric_name",
    values_to = "metric_score",
    values_drop_na = TRUE
  )

```
